### PR TITLE
FIX: Exposes image scripts for preprocessing

### LINKED ISSUE #26: Transparency of image preprocessing
```bash
>>> import this

...
Explicit is better than implicit.
...
```

Image preprocessing is currently not all transparent.  If users pass in oddly shaped images they might be surprised to find that performance is poor.  By exposing a more transparent interface for image preprocessing we cut down on the number of surprises.

### PR DESCRIPTION
**Pull request by sihrc**
Resolves #26

### CODE REVIEW

**Comment by anneCarlson** [comment]
Does the political test not work anymore because of the political fix to IndicoApi?

**Comment by sihrc** [comment]
Yep. But it's fixed and supposedly on its way or already in development

**Comment by anneCarlson** [comment]
Alright! This looks good, but I'm reluctant to merge it in until the tests pass, so, once we update IndicoApi?

**Comment by sihrc** [comment]
It was already merged in development. Merging dev into this branch and to run tests now.

**Comment by sihrc** [comment]
@anneCarlson  :+1:

**Comment by madisonmay** [comment]
So although this does make preprocessing more transparent I'm reluctant to merge this in and resolve the issue although it totally checks all the boxes.  

The primary issues come from:
    - People feeding in non-square images
    - Images that need cropping to be accurate

This allows people to scale images, but doesn't fix either of the two primary issues.  To be honest a docs fix is probably more important than merging something like this in.   Thoughts?

**Comment by sihrc** [comment]
What is our stance on non-square images? Are we trying to support it?

**Comment by madisonmay** [comment]
Going to close this for now, not as relevant at the moment.

**Pull request closed without merging**
