### PR TITLE
WIP: Madison/collection permissioning

### PR DESCRIPTION
**Pull request by madisonmay**
Reviewers: 
----------

- [x] @madisonmay
- [x] @sihrc 
- [ ] @anneCarlson 

What's the purpose of the PR?
-----------------------------

Description of changes
----------------------

Notes to reviewers
------------------

Keep in mind while reviewing code:
----------------------------------
- Is relevant code tested?
- Are added functions/methods documented?
- Separation of concerns (SOC)
- Don't repeat yourself (DRY) 
- Limit the number of positional arguments
- Is function/method length reasonable?
- Can code be broken down into smaller components?
- Where do added functions/methods belong?
- Are variable names descriptive?
- Are errors handled appropriately?
- Can logic be simplified?
- Does the code make sense in context? (expand the diff)

### CODE REVIEW

**Comment by madisonmay** [comment]
Now with tests!

**Comment by madisonmay** [comment]
However, tests will not pass until the remote is updated...

**Comment by sihrc** [comment]
Development?

**Comment by madisonmay** [comment]
Doh, thanks.

**Comment by madisonmay** [comment]
Closing and reopening.

**Pull request closed without merging**
